const CACHE="ftem-f32582a3c8";
const CORE=["./", "./index.html", "./fr.html", "./it.html", "./en.html", "./admin.html", "./manifest.webmanifest", "./assets/favicon.svg", "./assets/icon-192.png", "./assets/icon-512.png", "./assets/icon-180.png", "./assets/hero.jpg", "./assets/og-image.jpg", "./assets/swiss-ski-logo.svg", "./assets/sporticons/mono-skispringen.png?v=1bee3658", "./assets/sporticons/reserve-moguls.png?v=d9c20603", "./assets/sporticons/freeski-park-pipe.png?v=1189916a", "./assets/sporticons/mono-langlauf.png?v=f07d4500", "./assets/sporticons/skicross.png?v=365905b6", "./assets/sporticons/mono-nordische-kombination.png?v=1b344cc8", "./assets/sporticons/biathlon.png?v=1f094d86", "./assets/sporticons/ski-alpin.png?v=92721893", "./assets/sporticons/skispringen.png?v=929a63a2", "./assets/sporticons/mono-biathlon.png?v=8227fa54", "./assets/sporticons/snowboard-park-pipe.png?v=8bbd90f5", "./assets/sporticons/mono-snowboard-cross.png?v=81278b4a", "./assets/sporticons/mono-ski-alpin.png?v=dd6162b0", "./assets/sporticons/mono-freeski-park-pipe.png?v=2be39041", "./assets/sporticons/reserve-telemark.png?v=24bb0d59", "./assets/sporticons/langlauf.png?v=f430da0c", "./assets/sporticons/mono-snowboard-alpin.png?v=2f5c07d0", "./assets/sporticons/reserve-aerials.png?v=971752a2", "./assets/sporticons/mono-snowboard-park-pipe.png?v=52af446e", "./assets/sporticons/mono-skicross.png?v=f4e1292b", "./assets/sporticons/nordische-kombination.png?v=4da86645"];
self.addEventListener("install",e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting()));});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener("fetch",e=>{const req=e.request;if(req.method!=="GET")return;const url=new URL(req.url);if(url.origin!==location.origin)return;
  const isPage=req.mode==="navigate"||url.pathname.endsWith(".html")||url.pathname.endsWith("/");
  if(isPage){
    // Seiten: immer zuerst frisch vom Netz (kein "alte Version"-Problem mehr), Cache nur offline
    e.respondWith(caches.open(CACHE).then(async c=>{try{const res=await fetch(req);if(res&&res.status===200)c.put(req,res.clone());return res;}catch(_){const cached=await c.match(req);return cached||Response.error();}}));
    return;
  }
  e.respondWith(caches.open(CACHE).then(async c=>{const cached=await c.match(req);const net=fetch(req).then(res=>{if(res&&res.status===200)c.put(req,res.clone());return res;}).catch(()=>cached);return cached||net;}));});
